### ISSUE TITLE
Moneropedia links are broken in dev guides

### ISSUE THREAD

**Issue by 00-matt** [monero-project/monero-site#1054]
Moneropedia links in the dev guides show up as `@entry-name` instead of a link.

![moneropedia-1](https://user-images.githubusercontent.com/48835712/85704154-f3a32280-b6d7-11ea-8034-6b38159de574.png)
![moneropedia-2](https://user-images.githubusercontent.com/48835712/85704158-f43bb900-b6d7-11ea-9fae-9cde8c775cfd.png)

**Comment by erciccione** [comment]
I think that's happening because we changed the location of the developer guides, which are now in `/resources/developer-guides` instead of `_i18n/LANG/resources/devloper-guides`. I guess the `moneropedia.rb` script in `_plugins` needs to be adapted to catch the files in `/resources/developer-guides`.

**Comment by erciccione** [comment]
Fixed with #1122
