### ISSUE TITLE
Add the 'GUI guide' to the user guides

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1058]
The [guide of the GUI wallet](https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/monero-GUI-guide.md) could be added to the 'Wallets' section of the 'User Guides' page: https://web.getmonero.org/resources/user-guides

Instead of adding the guide itself, i think would be better to add a link to the guide on GitHub. We could list it with the other guides, but we would warn the users about the fact that they are clicking on an external link. This could be also useful in case we decide to add more external resources to that page.

As suggested on reddit: https://www.reddit.com/r/Monero/comments/hg60sb/new_release_of_the_guide_for_the_gui_wallet/fw1y9ur/

**Comment by MoneroArbo** [comment]
I also want to note that erciccione's guide overlaps with some of the other guides. For example, it overlaps completely for this one: https://web.getmonero.org/resources/user-guides/remote_node_gui.html

Others contain instructions for both CLI and GUI, so overlap partially, like this one: https://getmonero.org/resources/user-guides/view_only.html

I think it would be best not to have redundant documentation like this, especially since the existing stuff is somewhat dated.

**Comment by erciccione** [comment]
> I think it would be best not to have redundant documentation like this, especially since the existing stuff is somewhat dated.

I don't see that as a problem. The goal of the guides is different. The GUI guide aims to give a deep overview of how the GUI works, since it goes through the complete software, there will definitely be content that it's already in some specific guide.

**Comment by erciccione** [comment]
#1154 

> We could list it with the other guides, but we would warn the users about the fact that they are clicking on an external link. This could be also useful in case we decide to add more external resources to that page.

With #1145 external links will be flagged with an icon.
