### ISSUE TITLE
monero download with curl enforcing https broken

### ISSUE THREAD

**Issue by adrelanos** [monero-project/monero-site#1081]
`https://downloads.getmonero.org/gui/linux64` is the download link provided at `https://web.getmonero.org/downloads/`.

    curl --tlsv1.2 --proto =https --location --remote-name-all --remote-header-name --output /tmp/test https://downloads.getmonero.org/gui/linux64

> curl: (1) Protocol "http" not supported or disabled in libcurl

Dropping `/gui/linux64` works.

    curl --tlsv1.2 --proto =https --location --remote-name-all --remote-header-name --output /tmp/test https://downloads.getmonero.org

No error. But then it is not clear to me what would be downloaded.

**Comment by 00-matt** [comment]
I think that this is because you get a long chain of redirects, some of which are plain HTTP.

**Comment by adrelanos** [comment]
I guess so. Imo very worthwhile to fix since any intermediate redirect
to HTTP could be mitm'd.

**Comment by fluffypony** [comment]
FIXED! We originally support HTTP for updates.getmonero.org (used by the auto-updater), but now that it can handle HTTPS (and everyone's mostly updated since that change) we no longer require it. We've also enabled HSTS, applied for it to get added to the HSTS pre-load list, and enforced HTTP->HTTPS for everything on getmonero.org including all subdomains.

**Comment by fluffypony** [comment]
FIXED! We originally support HTTP for updates.getmonero.org (used by the auto-updater), but now that it can

**Comment by SarangNoether** [comment]
I just tested the original HTTPS query, and it redirects properly now.
