### ISSUE TITLE
BITEXBOOK exchange tickers update

### ISSUE THREAD

**Issue by 76o89e** [monero-project/monero-site#1089]
Hello,

Since XMR/ETH and XMR/UAH trading pairs have appeared on BITEXBOOK exchange (https://bitexbook.com/en/trading/xmreth, https://bitexbook.com/en/trading/xmruah), I want to ask you to update tickers on your "[Merchants](https://web.getmonero.org/community/merchants/)" page: at the moment only XMR/BTC, XMR/USD and XMR/RUB pairs are listed.

Thank you!

**Comment by erciccione** [comment]
@76o89e Since adding more trading pairs is not doable (if they start being too many they would go in a newline and that doesn't look nice), i simply removed the existing pairs `(XMR/BTC, XMR/USD, XMR/RUB)` and simply added `Multiple trading pairs`. see #1094. If you wish to suggest a better description, please feel free to do so, but keep it under 50 characters.

**Comment by 76o89e** [comment]
@erciccione Thank you for the explanation. Please add the following description then: BITEXBOOK (XMR/USD, RUB, UAH, BTC, ETH)

**Comment by erciccione** [comment]
That doesn't really make much difference in the long term, but i changed it for now, we will see what to do in the future.
