### ISSUE TITLE
Moneropedia links (created by _plugins/moneropedia.rb) are always lower case

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1352]

**Comment by wirrickelliot** [comment]
What's the expected behavior? Should they all be capitalized? From what I can tell, the Moneropedia plugin just preserves the capitalization of the terms provided in each Moneropedia entry, and the majority of them are lowercase. Several of them (Locally-unique host, Canonically-unique host, and Kovri) are capitalized and are displayed as such.

**Comment by erciccione** [comment]
> Should they all be capitalized?

They should be capital when at the beginning of a sentence or after a dot, lowercase if the word is in the middle of a sentence.

**Comment by wirrickelliot** [comment]
What do you think about using the matched term instead of the entry term in the gsub call? The capitalization could then be decided on a case-by-case basis instead of being dictated by the Moneropedia entry or any preceding punctuation.
```
content = content.gsub(/(\@#{term})((?=-#{lookahead})|(?![\w-]))/i) { |match_term| '<a class="info-tooltip" data-tooltip="' + entry[:summary] + '" href="/resources/moneropedia/' + entry[:file] + '.html" >' + match_term.gsub(/[@-]/, '@' => '', '-' => ' ') + '</a>' }
```

This would help with situations where the Moneropedia links aren't at the beginning of a sentence such as the video section under the FAQ:

![image](https://user-images.githubusercontent.com/23042683/108885017-48839980-75d5-11eb-866d-a08a6b5f7ead.png)

The downside to this, however, is that any existing capitalization errors would need to be fixed manually. For instance, changing `@ring-ct` to `@Ring-CT` in the example above.

**Comment by erciccione** [comment]
Good idea. I was slightly worried about how the other languages would have reacted (especially the ones not using latin characters), but i tested your patch quite extensively and there seem to be no problems.

Would you PR your patch? As you said, capitalization errors are not a big deal and we can fix them when we find them.
