### ISSUE TITLE
REMOVE scammer actio-fast-pay.net from the list of merchants

### ISSUE THREAD

**Issue by danvctr** [monero-project/monero-site#1517]
#### What's the name of the business?

actio-fast-pay.net

#### What's the URL of the website?

actio-fast-pay.net

#### Write a brief description of your business/service (max 50 characters)

I sent well over the minimum required XMR (>3.5 XMR) to actio-fast-pay.net in exchange for BTC. After 21 confirmations I still haven't received my BTC. Their website claims their support responds in 15 - 60 minutes but I haven't heard back from them at all after two seperate emails. I was scammed out my XMR. 

#### Comment

I'm deeply saddened by how little due diligence was done before listing this exchange to the official Monero website. See [Issue 1388](https://github.com/monero-project/monero-site/issues/1388) for what I'm referring to. If there's any way that someone knows if how I can recover my XMR please let me know.

**Comment by actio-fast-pay** [comment]
Hello
You did not create an exchange transaction with us!

**Comment by actio-fast-pay** [comment]
Please remove the administration provocation of the user, because what he writes is not true, because he did not create our transaction for the exchange!

**Comment by actio-fast-pay** [comment]
We suspect that this is the action of unscrupulous competitors, because we have not had any complaints from our users. And this complaint is just a text written by a user without any proof, so they can blame any service and remove all unwanted ones from the merchant list.

**Comment by erciccione** [comment]
@danvctr i'm sorry that you lost your money, but as we point out in multiple places in the Merchants page, we don't do any vetting of the merchants and this is not an "official" list. We only check that the merchants accept Monero. As you can imagine it's not really feasible to make a technical investigation of all merchants. The final user has the duty to research the service they want to use, especially for big amounts.

While i'm saddened by the events, you shouldn't blame us, since you ignored the two warnings and admitted you haven't made any research on the merchant before using it.

**Comment by actio-fast-pay** [comment]
> @danvctr i'm sorry that you lost your money, but as we point out in multiple places in the Merchants page, we don't do any vetting of the merchants and this is not an "official" list. We only check that the merchants accept Monero. As you can imagine it's not really feasible to make a technical investigation of all merchants. The final user has the duty to research the service they want to use, especially for big amounts.
> 
> While i'm saddened by the events, you shouldn't blame us, since you ignored the two warnings and admitted you haven't made any research on the merchant before using it.

This user did not create a transaction at us to exchange, and he did not lose anything is a simple provocation.

**Comment by danvctr** [comment]
> @danvctr i'm sorry that you lost your money, but as we point out in multiple places in the Merchants page, we don't do any vetting of the merchants and this is not an "official" list. We only check that the merchants accept Monero. As you can imagine it's not really feasible to make a technical investigation of all merchants. The final user has the duty to research the service they want to use, especially for big amounts.
> 
> While i'm saddened by the events, you shouldn't blame us, since you ignored the two warnings and admitted you haven't made any research on the merchant before using it.

I just would appreciate more then a simple "yup this website says Monero on their homepage" to prevent this from happening to someone else. 

Maybe wait until the exchange has been established for a few months with some 3rd party feedback available.

**Comment by danvctr** [comment]
> > @danvctr i'm sorry that you lost your money, but as we point out in multiple places in the Merchants page, we don't do any vetting of the merchants and this is not an "official" list. We only check that the merchants accept Monero. As you can imagine it's not really feasible to make a technical investigation of all merchants. The final user has the duty to research the service they want to use, especially for big amounts.
> > While i'm saddened by the events, you shouldn't blame us, since you ignored the two warnings and admitted you haven't made any research on the merchant before using it.
> 
> This user did not create a transaction at us to exchange, and he did not lose anything is a simple provocation.

Also, I can't believe you'd have the audacity to crawl out of your hole in the wall and straight up lie after stealing that much money from someone. Whoever raised you is truly ashamed.

**Comment by erciccione** [comment]
> I just would appreciate more then a simple "yup this website says Monero on their homepage" to prevent this from happening to someone else.

Do you have suggestions? Consider that making extensive researches on new merchants would require a lot of resources (that we don't have) and even if we would do that, the problem would be far from resolved. A malicious vendor can easily run their business legitimately for a couple of months before starting to scam, or they could fabricate positive reviews.

Currently, the only safe way for people to not be scammed is to research the business themselves (which should be done anyway since you are trusting strangers with your money). Still, we are considering restricting the listing of merchants in the "Exchanges" section.

In the meantime what we can do is to make sure the disclaimers are visible and the wording clear enough, that's why i opened #1518.

**Comment by danvctr** [comment]
> Hello
> You did not create an exchange transaction with us!

Hey man,

I'm not sure if you're monitoring this thread or not, but it's worth trying.

All I'm asking is, could I please get half of what I was supposed to get from your exchange? I barely slept last night because I don't know how I'm going to handle this loss. 

I sent you a significant portion of my net worth last night, expecting BTC in return.

I understand we all need to eat, and you got me. So well done. But please have some human decency and empathize with me, I'm sure you can understand someone financially struggling. 

Thanks for reading my note, 

Dan Victor

**Comment by phoony** [comment]
Hey,
I can confirm that this so called "exchange" scammed me too. A removal of this site should be arranged as soon as possible before more people fall for it.
