### ISSUE TITLE
hangouts: replace facebook with telegram

### ISSUE THREAD

**Issue by alreadyburnt** [monero-project/monero-site#1553]
Reasons:
- no one interested in monero uses facebook
- company with the worst reputation for privacy ever
- not even bitcoin.org lists facebook
- telegram isn't listed at all although it's very active and has a good portion of the community
- on telegram people can find immediate help

**Comment by erciccione** [comment]
We list telegram in the footer, not in hangouts. I don't remember the details, but it was decided to not put in on hangouts because of the large amount of spam.

> no one interested in monero uses facebook

This is sadly not true. A portion of the community thinks that we have to reach people where they are and facebook is one of the main social media. I too agree that feels weird to list it, but i don't think this is going to change, as many in the active community are willing to make heavy compromises in order to onboard more people.

**Comment by alreadyburnt** [comment]
> We list telegram in the footer, not in hangouts. I don't remember the details, but it was decided to not put in on hangouts because of the large amount of spam.

Yeah, I saw it. In fact, I was wondering what on earth the telegram group was doing in the footer of every page. There is Hangouts for a reason.

> This is sadly not true. A portion of the community thinks that we have to reach people where they are and facebook is one of the main social media. I too agree that feels weird to list it, but i don't think this is going to change, as many in the active community are willing to make heavy compromises in order to onboard more people.

I can understand, however I don't think it's appropriate to jeopardize the Monero reputation just to get it out there as quickly as possible. This can raise a big red flag for both those who are looking to join the community and investors. And besides, in no way would Bitcoin be taken as seriously if it had a facebook profile. Just no way.

**Comment by erciccione** [comment]
> There is Hangouts for a reason.

Well you are not wrong. If we list it, should be placed in the appropriate section.

**Comment by erciccione** [comment]
#1614 removes Telegram from the footer and adds the logo to the hangouts page. I don't think there is interest in removing Facebook from the Hangouts page. I would consider this resolved once 1614 is merged.
