### ISSUE TITLE
Add Canada Virtual Office to the list of merchants

### ISSUE THREAD

**Issue by cvoadmin** [monero-project/monero-site#1683]
#### What's the name of your business?

Canada Virtual Office

#### What's the URL of the website?

[https://canadavirtualoffice.com](https://canadavirtualoffice.com)
#### Write a brief description of your business/service (max 50 characters)

Corporate address service

#### Enter the URL where a Monero mention can be found

[https://register.canadavirtualoffice.com/cash-registration.pdf](https://register.canadavirtualoffice.com/cash-registration.pdf)

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

[Register](https://register.canadavirtualoffice.com), click "or use cash," should redirect to [https://register.canadavirtualoffice.com/cash-registration.pdf](https://register.canadavirtualoffice.com/cash-registration.pdf)

**Comment by erciccione** [comment]
Would be better if we could add a mention of Monero somewhere else in the website, like the footer. Having to register and then click on "use cash" to see a mention of Monero is far from optimal. People could click on your service from our merchants page and left soon after because they think you don't actually accept Monero. That's just a suggestion, I'm ok with adding this to our list.

**Comment by cvoadmin** [comment]
Thanks for the feedback.

**Comment by erciccione** [comment]
#1687
