### ISSUE TITLE
Remove CoinCat - Buy and sell crypto in minutes from the list of merchants

### ISSUE THREAD

**Issue by Karlioni** [monero-project/monero-site#1697]
#### What's the name of the merchant you are asking to remove?

CoinCat - Buy and sell crypto in minutes

#### What's the URL of their website?

https://coincat.in

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [x] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://coincat.in/

#### Additional comments

I created the exchange for 12.48 XMR, paid according to the instructions indicated on the sayte, after the order is deleted, wrote to support on the website, received the answer that the order does not, and wallet XMR which was to pay does not belong to their service.

**Comment by erciccione** [comment]
ACK

**Comment by CoinCatEx** [comment]
This user hadn't contacted our support. We have no orders for this sum 12.48 in past 3 weeks.

You can check out lots of reviews of our exchange here:
https://exchangesumo.com/exchanger/933/CoinCat/
https://kurs.expert/ru/obmennik/coincat-in/feedbacks.html
https://bitcointalk.org/index.php?topic=5168201.20

There are lots of exchange listings and forums we are listed on. Please revert this commit since we have no deals with this user.

**Comment by CoinCatEx** [comment]
@erciccione
