### ISSUE TITLE
Add bounties.monero.social

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1880]
https://bounties.monero.social/ is a new platform/dashboard that allow people to offer bounties for features or ideas they would like to see implemented in Monero. We should add a mention somewhere on the website.

**Comment by carrington1859** [comment]
I think it should be listed equally alongside the CCS wherever that is linked on the site. The payouts are ultimately controlled by Core in either case, they are just different models of crowdfunding.

**Comment by carrington1859** [comment]
It is also worth noting that there has been a Cambrian explosion of crowdfunding systems/ideas in recent months. Here are the examples I'm aware of.

Plowsof's wishlist-as-a-service (https://github.com/plowsof/xmr-wishlist-aaS)

This tool has been used by the following projects to set up independent crowdfunding

Plowsof's personal wishlist (https://plowsof.github.io/)
Monerujo (https://funding.monerujo.app/)
XMR Community art fund (https://moneroart.neocities.org/)
XMR.radio (https://xmr.radio/funding)

Plowsof also created a directory of various devs/projects with donation/contact info (https://plowsof.github.io/monerodevs/) & a BCH Flipstarter proposal to make the wishlist system multi-coin including stablecoins (https://wishlist.monerodevs.org/).

Outside Plowsof's efforts there are also the following:

Haveno bounties (https://github.com/orgs/haveno-dex/projects/2)
MAGIC Grants (https://www.magicgrants.org/) *Site seems broken at this moment*

I'm not suggesting that all of these ideas should get equal booking with the CCS, but it worth having a discussion of if/how getmonero.org should promote these independent crowdfunding efforts.

Ultimately I think something like the monerodevs directory should be the aim. It seems to modeled on https://bitcoindevlist.com/ and the PoC was created in response to a bounty (https://bounties.monero.social/posts/7/setup-monero-dev-list-website). The bounty does specify "maintain a repo", but I'm not sure yet how actively maintained the project will be going forward.

**Comment by carrington1859** [comment]
17:00:00 _carrington[m]> Hey everyone it is meeting time! Here's an agenda:
17:00:01 _carrington[m]> https://github.com/monero-project/meta/issues/625
17:00:18 _MrSenshi[m]> _BusyBoredom[m]> "If this works by offline..." _- No?
17:00:28 _carrington[m]> 1. Introduction
17:00:56 _plowsof[m]> hi
17:00:59 _tobtoht> hi
17:01:10 _crypto_grampy[m]> 👋
17:01:11 _carrington[m]> This is a meeting to discuss whatever is going on in the Monero community. We can discuss CCS proposals, workgroup reports and any other relevant issues
17:01:14 _mj-xmr[m]> Hello!
17:01:24 _carrington[m]> 2. Greetings
17:01:25 _crypticentertain> Hello
17:01:33 _carrington[m]> Howdy
17:01:42 _Rucknium[m]> Hi
17:01:49 _ErCiccione> hi
17:01:56 _sgp_> Hello
17:02:18 _crypticentertain> Litesh this side from Cryptic Entertainments
17:02:18 _justverify[m]> Hi everyone
17:02:24 _sudo_ki[m]> ✌️
17:02:31 _carrington[m]> 3. Community highlights
17:02:31 _carrington[m]> Does anyone have any brief community highlights to discuss? Bigger issues can be left for the open time at the end of the meeting
17:02:51 _ajs_[m]> hi
17:03:53 _mj-xmr[m]> A small note for d), my proposal, before we move do b), OSPEAD: my proposal will be supporting OSPEAD.
17:04:06 _mj-xmr[m]> but not only, if more researchers come by.
17:04:17 _carrington[m]> I'll take this opportunity to plug https://www.monero.observer/ for keeping up with goings on, especially if you don't want to browse Reddit. escapethe3ra  is doing a good job there.
17:04:32 _ajs_[m]> I posted an updated on XMR.radio https://www.reddit.com/r/Monero/comments/qlf16e/xmrradio_quarterly_transparency_report/
17:04:48 _mj-xmr[m]> carrington[m]: I can recommend it. A very lightweight page.
17:05:47 _carrington[m]> Xmr.radio is pretty awesome also
17:06:17 _carrington[m]> 4. CCS updates
17:06:35 _carrington[m]> a. Italian Mastering Monero
17:06:45 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/251
17:06:58 _carrington[m]> I'm not sure if the proposer is here
17:07:40 _carrington[m]> The most recent comments suggest there might be a change of plan needed so maybe this should sit for now
17:08:28 _justverify[m]> Hi everyone. This is my proposal. I’m going to translate the first 4 chapters and then wait for the release of the second edition
17:08:28 _carrington[m]> I'll give a short while for comments and then move to the next proposal
17:09:11 _carrington[m]> Oh cool. Does that mean the CCS is going ahead at a later date?
17:09:27 _carrington[m]> I.e. when 2nd edition is coming up
17:10:05 _sgp_> SerHack: ^
17:10:26 _justverify[m]> carrington[m]: Yes that’s my plan. Going ahead right now would be nonsense since the 2 edition is coming up
17:10:56 _carrington[m]> Cool, could you please drop a comment on the proposal clarifying this plan?
17:11:23 _carrington[m]> b. OSPEAD - Fortifying Monero Against Statistical Attack
17:11:37 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/255
17:11:45 _justverify[m]> carrington[m]: Sure
17:11:51 _carrington[m]> https://www.reddit.com/r/Monero/comments/py8ub3/ccs_proposal_ospead_fortifying_monero_against/
17:12:06 _Rucknium[m]> There have been some developments on OSPEAD:
17:12:06 _Rucknium[m]> https://www.monero.observer/articmine-isthmus-weigh-rucknium-ospead-proposal-feasibility/
17:12:53 _Rucknium[m]> ^ The summary of that article is that ArticMine believes my proposal is feasible, but wants to see some small modifications. Isthmus supports the proposal and suggested some extensions.
17:13:01 _carrington[m]> It seems there is consensus amongst the people who have read the vuln report that the work is worthwhile and important
17:13:54 _carrington[m]> I don't see much point in waiting until "doc A" is published before moving this to funding required
17:14:01 _Rucknium[m]> I think that is true. I do not yet have feedback from binaryFate, however. He has been busy with IRL work though.
17:14:35 _carrington[m]> But if people want to publicly verify this stuff before donating they can just hold off and donate later
17:14:38 _Rucknium[m]> binaryFate has had my HackerOne submission for over a month.
17:15:22 _sgp_> I think this should be moved. The process partially because of the VRP has been quite messy to say the least, but the CCS should be moved in any case
17:15:30 _ArticMine> I have not problem with moving this to funding stage
17:15:33 _ArticMine> no
17:17:00 _carrington[m]> If no one has objections I'll move on
17:17:08 _carrington[m]> c. Monero Community Anthem
17:17:13 _Rucknium[m]> Ok great. I can make appropriate edits to the CCS proposal text ASAP, e.g. change "mixin" to "decoy", incorporate suggestions, finalize the XMR amount, etc.
17:17:16 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/259
17:17:49 _crypticentertain> That's my proposal. Please listen to our first version of monero anthem
17:17:58 _carrington[m]> Rucknium[m]: I guess you can decide yourself if you want to extend it by a couple of weeks as isthmus suggested
17:18:18 _crypticentertain> https://music.youtube.com/watch?v=bE-WPYKUNsM&feature=share
17:18:41 _Rucknium[m]> I think I will add 1.5 weeks. I think isthmus makes a good point -- don't have tunnel vision.
17:18:44 _crypticentertain> https://open.spotify.com/track/3C5HdGjCirqtAaEqBUPv76?si=6f710e4ec8ae4d50
17:18:55 _ErCiccione> carrington[m]: i initially downvoted it by actually i don't care
17:19:36 _carrington[m]> Do people have any questions about the scope and requested amount?
17:20:05 _carrington[m]> Requested amount is 20 XMR
17:21:07 _crypticentertain> We've released this track on multiple streaming platforms. The funds will be used to make 4k quality music video as well as remastered version of monero anthem
17:21:56 _ArticMine> How will it be licensed?
17:21:58 _crypticentertain> We use the following cameras for video shooting:... (full message at https://libera.ems.host/_matrix/media/r0/download/libera.chat/491f1109cdf5a9d49c3694643f3c54518387f14c)
17:23:01 _carrington[m]> A quick plug for the Monero Community Art fund which has a system for crowd funding art/media: moneroart.neocities.org
17:23:26 _crypticentertain> It's an original artwork. We own the complete license. The community can use it anywhere anytime and there won't be any copyright claims or strikes.
17:24:02 _ArticMine> That is great, but it should be made explicit with a Free Culture license 
17:24:52 _crypticentertain> It would be a royalty free track and no approval will be needed to use this track 
17:25:23 _ArticMine> with GPLv3 compatibility
17:25:30 _crypticentertain> ArticMine: Yes. Definitely! that's my vision
17:25:44 _Rucknium[m]> crypticentertainments: I believe you can explicitly give the track and music video a specific Creative Commons license
17:26:33 _crypticentertain> Rucknium[m]: Yes. Absolutely. We'll publish this under common license.
17:27:16 _carrington[m]> Well I think of you can add that to the proposal so that it is a condition of payout then that addresses those concerns
17:27:25 _mj-xmr[m]> "Creative Commons License" is a given name. It's not a common license. I'm sorry if this sounds offensive :)
17:28:28 _crypticentertain> carrington[m]: Yes. I'm adding this in the comment section
17:29:28 _carrington[m]> d. mj part time dev for Q4 2021
17:29:40 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/266
17:30:40 _carrington[m]> Also, crypticentertainments I think it would be a good idea to make a reddit post for your proposal if you haven't already
17:31:15 _mj-xmr[m]> So I've been doing this simulator for 9 years now, and am more of a practitioner than a researcher, so I just deliver tools for the researchers. I have a lot of exp here and continuously improve the runtime speed, etc., just like I do for Monero, but here I don't have to ask nobody to merge my PRs.
17:31:33 _ArticMine> I would suggest https://creativecommons.org/licenses/by-sa/4.0/ or something more permissive if desired 
17:31:55 _mj-xmr[m]> I will also not be doing JUST the simulator, as the usual Monero firefighting duties also have to be done by someone.
17:32:03 _crypticentertain> carrington[m]: Sure. I'll make one and share in the comment section of the proposal.
17:32:53 _mj-xmr[m]> Regarding the license, I'm strongly considering Affero GPLv.3, but I'm hoping, that I can count on your continuous support, since as the saying goes: "An Open Source Software gets sold only once..."
17:33:26 _mj-xmr[m]> (and Affero so that nobody can close the functionality through a web interface)
17:34:02 _Rucknium[m]> Here's my comment on mj-xmr  's proposal, by the way:
17:34:02 _Rucknium[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/266#note_12496
17:34:02 _Rucknium[m]> Hmm, the # link doesn't work too well
17:34:06 _mj-xmr[m]> We're already discussing the details with Rucknium 
17:34:12 _mj-xmr[m]> Beat me to it.
17:36:11 _carrington[m]> Any questions/comments on the proposal?
17:36:49 _carrington[m]> I think a reddit post would be good for this too if there isn't one already
17:37:42 _carrington[m]> Seems uncontroversial anyways, I'll move along
17:37:50 _carrington[m]> e. Feather wallet dev for 3 months
17:38:05 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/267
17:38:12 _tobtoht> I shared the proposal on Reddit a few days ago and received positive feedback: https://old.reddit.com/r/Monero/comments/qmufvc/ccs_proposal_continued_feather_wallet_development/
17:38:19 _tobtoht> Here to answer questions should anyone have any
17:39:20 _carrington[m]> I have to admit I've not tried Feather out but the comments & feedback I've seen have been universally positive
17:40:10 _Lovera[m]> carrington[m]: The best wallet desktop 😎
17:41:28 _crypto_grampy[m]> Really like what you're doing tobtoht .  My only requests are adding in config support for XMRig and Monero URI support.  How do you go about prioritizing what features to add?
17:42:30 _crypticentertain> _crypticentertain> "Yes. I'm adding this in the..." _- We have made the amendments in the proposal about the creative commons license and we are creating a reddit post as well to take inputs from the community.  
17:43:30 _carrington[m]> We are getting to the more recent proposals so I guess maybe people want more time to look at these before moving them?
17:43:38 _carrington[m]> Finals proposal was made 1 day ago
17:43:49 _tobtoht> crypto_grampy[m]: "My only requests are adding in config support for XMRig and Monero URI support." -> Yep, both are on the to-do list.
17:44:26 _tobtoht> crypto_grampy[m]: "How do you go about prioritizing what features to add?" -> Last in, first out. Mostly.
17:44:29 _carrington[m]> Now that feather is out of beta I'll give it a whirl
17:44:53 _carrington[m]> Last proposal:
17:44:53 _carrington[m]> https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/268
17:45:43 _Lovera[m]> Hello guys, Lovera here. This is my proposal!!
17:45:58 _carrington[m]> I'll suggest a reddit post here as well. Best that as many people in the community see proposals as is possible.
17:47:31 _carrington[m]> It would be good to have some Spanish speaking community members feedback on this
17:47:32 _Lovera[m]> carrington[m]: Ok! I will do a post in Reddit today or tomorrow 👍🏼
17:48:40 _carrington[m]> 5. Documentation/UX improvement ideas
17:49:23 _carrington[m]> Several people have expressed concern with outdated/incomplete documentation and onboarding materials
17:49:38 _Rucknium[m]> #moneroes:monero.social is the Spanish channel. Quite active.
17:51:02 _crypto_grampy[m]> carrington[m]: ErCiccione: can you speak at all to this one?  What are the challenges and what do you think would help in this area?
17:51:06 _Rucknium[m]> I see people come into #monero-dev:monero.social wanting to contribute, but we give them no clear path.
17:51:18 _carrington[m]> There is a new room #monero-ux:monero.social  for any initiatives in this area
17:51:26 _ErCiccione> ^ this
17:51:44 _ErCiccione> I think having a workgroup dedicated to improve Monero's UX could be very beneficial
17:52:04 _ErCiccione> we need somebody to work on the documentation for both users and devs
17:52:15 _ErCiccione> https://github.com/monero-project/monero-site/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%93%9A+docs%3A+dev+guides%22
17:52:15 _ErCiccione> especially https://github.com/monero-project/monero-site/issues/1434
17:52:22 _ErCiccione> https://github.com/monero-project/monero-site/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%93%9A+docs%22
17:52:30 _ErCiccione> https://github.com/monero-project/monero-site/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%93%9A+docs%3A+user+guides%22
17:53:30 _ErCiccione> Personally i would he happy to support a CCS with the goal of refreshing at least the dev docs
17:54:18 _crypto_grampy[m]> ErCiccione: It would be great if it was akin to MRL or Monero-dev.  Very topic focused on docs, and improving onboarding and overall experience for new users, doc-writers, merchants and devs, etc
17:54:31 _carrington[m]> Maybe it would be a good idea to create a few bounties for docs, and then if a suitable person is found that way they can make a CCS for a bigger update?
17:55:04 _ErCiccione> Bounties work in my experience
17:57:42 _carrington[m]> Maybe a bounty for updating all the RPC guides?
17:58:08 _crypto_grampy[m]> _Rucknium[m]> "I see people come into #monero-..." _- What do you think is a good solution for this
17:58:15 _carrington[m]> But then it's hard to determine who gets the bounty if multiple people make pull requests
17:59:33 _Rucknium[m]> crypto_grampy: I'm not really sure since I'm not a software developer. However, isthmus has suggested looking at what other coins do and seeing if we can incorporate their lessons.
18:01:07 _carrington[m]> Well as we are already at an hour people can continue these discussions afterwards or in #monero-ux:monero.social  / #monero-bounties:monero.social 
18:01:41 _mj-xmr[m]> Thanks for an awesome moderation :)
18:01:46 _BusyBoredom[m]> I think a good way to onboard new programmers is to (1) have excellent documentation and (2) have a few github issues marked "beginner". The rest takes care of itself, beginners just need starting points. 
18:02:26 _crypto_grampy[m]> BusyBoredom[m]: definitely agree on the marked for beginner issues.  even for documentation 
18:02:33 _carrington[m]> 6. Workgroup reports
18:02:38 _Rucknium[m]> Something to think about: Would people be interested in a funding system independent of CCS that would focus specifically on research to improve Monero's core protocol?
18:02:51 _crypto_grampy[m]> mj-xmr[m]: Yeah bravo carrington  ! 😄
18:03:09 _mj-xmr[m]> I thought we're over >__
18:03:28 _carrington[m]> We can keep going with the other stuff on the agenda if people want
18:03:34 _Rucknium[m]> I also thought we were over 🤔
18:03:53 _Rucknium[m]> We haven't had a meeting in N weeks, so I would be fine to keep going
18:03:54 _carrington[m]> I'll leave the floor open if any workgroups want to do some quick updates or shilling
18:04:46 _carrington[m]> Floor is also open for "open ideas"
18:06:12 _carrington[m]> Meta topic: should these meetings be every 2 weeks? Would people prefer a different meeting structure? 
18:06:16 _Rucknium[m]> Would people be interested in a funding system independent of CCS that would focus specifically on research to improve Monero's core protocol?
18:06:35 _carrington[m]> Yes, but who would custody?
18:07:13 _Rucknium[m]> I'm not sure. Suggestions?
18:07:48 _carrington[m]> MAGIC maybe? 
18:07:57 _carrington[m]> It has been offered iirc
18:08:45 _Rucknium[m]> Maybe, but that would probably require KYC for the recipients.
18:10:47 _carrington[m]> Well we all trust core with the CCS and bounty wallets so I think trusting a "MRL core" isn't a crazy idea
18:11:24 _carrington[m]> But I guess this is more a MRL meta discussion, so it can move to #monero-research-lounge:monero.social  for the purposes of ending logs
18:11:49 _tobtoht> On the topic of documentation, I recently put up documentation for Feather Wallet: : https://docs.featherwallet.org/
18:11:55 _tobtoht> Would love to hear your thoughts
18:11:56 _ArticMine> My take on funding is that there needs to be different options with the current CCS being one of them
18:12:13 _ArticMine> This is in the interest of decentralization
18:12:27 _carrington[m]> I'll try and do another of these meetings in 2 weeks if people want that

**Comment by erciccione** [comment]
I don't think it's in the scope of Getmonero to add all bounty systems. That would also need somebody to maintain such list. That rises the question of what criteria of addition should be used.

**Comment by carrington1859** [comment]
IMO, the "Crowdfunding" links should point to a page featuring the CCS & the bounties site with brief explanations of how they each work and what they are for. I'd also consider adding the monerodevs.org site alongside them as that links out to many worthy projects and dev tipjars.

**Comment by carrington1859** [comment]
As an update to this discussion, the MAGIC Monero fund will soon be up and running. After it has proven itself, I think it deserves to be listed alongside the other options.

https://magicgrants.org/funds/monero/
https://www.reddit.com/r/Monero/comments/r8vbqj/announcing_the_magic_monero_fund/
