### ISSUE TITLE
documentation of the start_height field to the refresh RPC method is incomplete

### ISSUE THREAD

**Issue by dimalinux** [monero-project/monero-site#2084]
Reference:
https://github.com/monero-project/monero-site/blob/7535c4c62623166af4ce12033e30af2d7d19c40b/resources/developer-guides/wallet-rpc.md#L2514

Right now the description of `start_height` to the `refresh` wallet RPC method says:
> The block height from which to start refreshing.

It should say something like:
> The block height from which to start refreshing. Passing no value or a value less than the last block scanned by the wallet refreshes from the last block scanned.

This change will prevent anyone from incorrectly thinking that `refresh` can  be used to force rescan the block chain.

**Comment by plowsof** [comment]
Thank you. Confused me also.. its clear that its meant to be used in combination with auto_refresh disabled OR - skip / fast forward the sync process (i believe featherwallet utilises this for insta-syncing if the user is certain theyv'e received no funds since the last time they opened their wallet). I've updated my PR with your addition and credited you.
