### ISSUE TITLE
Change version structure of downloads page

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-site#761]
In my opinion, the current structure of the downloads page is quite misleading. It may work properly if both versions match, but not in situations where the CLI version is ahead of the GUI version (a situation we're currently experiencing). 

I propose to list the versions for both the CLI and GUI separately to avoid any confusion.

**Comment by el00ruobuob** [comment]
Do you mean we should state of a latest cli version vs. Latest gui version?
So a listing per type, Cli first then Gui, should be more appropriate to a listing per os.

**Comment by wowee2** [comment]
Thank you finally ..so its not just me.

I was under the impression that the GUI was already made since the site says Under Linux64
Current Version: 0.12.2.0 Lithium Luna
which is misleading if CLI is made but GUI is not made.

Please label version on top of each OS version
https://github.com/monero-project/monero/issues/4044

**Comment by wowee2** [comment]
For example see here
![monero gui](https://user-images.githubusercontent.com/40521956/41811079-f0b4f5dc-7708-11e8-8d51-4f1b2ceffb0d.jpg)

**Comment by el00ruobuob** [comment]
Already solved by @rehrar in #766 @wowee2 could you close @dEBRUYNE-1 or @erciccione ?

**Comment by erciccione** [comment]
+resolved
