### ISSUE TITLE
request update mining pools link

### ISSUE THREAD

**Issue by ephz3nt** [monero-project/monero-site#774]
hi ,
 i see the pool lists moneropools.com is long time nobody manager,i'm submitted few message try append my pool https://noobxmr.com but nobody reply, i see a new active monero pool lists https://miningpoolstats.stream/monero , i submit my pool url one day later , its on the lists, i recommend change https://miningpoolstats.stream/monero in https://getmonero.org/get-started/mining/

**Comment by el00ruobuob** [comment]
To be listed on moneropools, your pool should have found at least one block. That's in their conditions. Therefor you're perhaps not getting answers because they decided to ignore you the same way you decided to ignore their condition. Anyway, has anyone been in touch with them recently? Are they really unmanaged? If so let's consider your proposal.

**Comment by Ephzent** [comment]
sry, maybe my bad
i will send message again after fund 1 block and thank your reply.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab.
