### ISSUE TITLE
Hangouts page enhancement

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#775]
It has been discussed during monero community meeting held on 2018-06-23 that hangouts page should contains more channels, to more plateform.

I open this issue to discuss it:
- What platform?
  - Telegram
  - Slack or not slack?
  - Whatsapp?
- What Channels/Groups?

**Comment by erciccione** [comment]
In my opinion we shouldn't advertise closed source platforms like slack. They are not made for open source projects and we have better alternatives we shoul advice (our own MatterMost istance for example). Anspiring contributors/community member should be redirected to this alternatives. This doesn't mean that we should drop them completely, just discourage their use.

+enhancement
+discussion

**Comment by el00ruobuob** [comment]
I share your opinion @erciccione however vp11 had a good point during the meeting. So if some *disgusting* platforms are used by a large number of community members, why not adding them to the page? We could have a disclaimer to explain why slack & whatsapp are bad, and why they should prefer IRC or Telegram, but our common goal is adoption right?

**Comment by curumimxara** [comment]
I'm pretty sure we can find a middle ground so everyone can be happy. I completely agree that since the Monero Project is open source and promotes FOSS we should focus on these communication platforms. But we cannot and we should not close our eyes to other communication platforms, even more if we're talking about platforms that are exclusively used in specific geographical territories.

It's completely irrelevant that XChat (IRC) or MatterMost are open source if, for example, no one in a certain country uses it. Or if there are no decent translated options of these software for a specific group of people.

We're talking about the Hangouts page. So let's use some critical thinking here: what's the main goal of such page? To attract people who want to contribute, or know more about the project, so we can grow as a global community.

So let's work for that goal. I think that in the Hangouts page we could first list the open source communication platforms, such as IRC channels on Freenode and the MatterMost instance. We should insert a notice saying that the Monero Project recommends using these channels since they're open source, free, etc.

We should then list all the relevant channels for specific geographical territories. If in Japan everyone is using LINE and a Japanese created a LINE Monero Group, then we should link it, because Japanese people are used to use LINE and that's what they want to use. In Brazil people use WhatsApp more than anything else. I've created a WhatsApp Group for Monero and a lot of people use it. Maybe in Russia the most prominent channel is Telegram, so we should list the Telegram Group in the Russian version of the website.

I do not agree that we should discourage the use of such platforms. We should encourage the use of the open source and "official" channels, but no discourage the other ones. This is a question of technological culture. We cannot and we should not force people to use a software or platform that they're not used. Trying to get people into crypto and Monero is already hard enough, if people need to install and learn a new software just to be able to communicate with other people then we're going in the wrong direction.

Remember, we're not talking about a closed-source wallet, nor a closed-source custodial wallet. We're talking about closed source messaging platforms that are already vastly used in these specific countries. To not promote or to discourage the creation of local communities in these communication platforms sound like a bad decision. We should promote it in the Hangouts page to get more people into Monero.

**Comment by rehrar** [comment]
After some thought, I agree with @curumimxara, the way to go is to encourage the platforms we want rather than discourage platforms we don't.

**Comment by Electricsheep01** [comment]
#openalias isn't listed on the hangouts page fyi

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
