### ISSUE TITLE
Moneropedia - Mix-in

### ISSUE THREAD

**Issue by palexande** [monero-project/monero-site#83]
Need to add this term to Moneropedia.  Unknown if anybody is working on this term.  I can add it if nobody else is.

**Comment by SamsungGalaxyPlayer** [comment]
Seconded. Newcomers often have questions about mixins, and it is a good idea to clarify the difference between Monero's use of mixins and mixing/tumbling services.

**Comment by SamsungGalaxyPlayer** [comment]
Can we adapt the definition from [Bitcointalk](https://bitcointalk.org/index.php?topic=753252.msg9985441#msg9985441) and use what's below?

The mixin count refers to the number of other signatures (aside from yours) in the ring signature that authorizes the transaction. A default mixin of 4 means that there are 5 total signatures. Someone looking at a transaction with a mixin of 4 has no way of knowing which of the five signers is the true sender.

A higher mixin number will typically provide more privacy than a lower mixin number because it will provide a greater amount of plausible deniability. However, reusing an odd, recognizable mixin for your transactions will make your transactions stand out.

The GUI allows users to select a mixin between 4 and 25. The CLI allows users to select any value permitted by the network.

**Comment by palexande** [comment]
Alright, I'll see what I can do.

**Comment by jonathancross** [comment]
Hi @palexande Are you still working on this?

**Comment by palexande** [comment]
I wanted to wait a bit and see how the ring size term turned out.  Looks like it has been updated?

**Comment by palexande** [comment]
I'm closing this issue since it looks like ring-size is now being used fairly universally now.
