### ISSUE TITLE
Please add to Monero merchants

### ISSUE THREAD

**Issue by MInersForLess** [monero-project/monero-site#859]
Hello. We sell ASIC miners via cryptocurrencies with bulk discounts. This includes monero and we would like to be added to the list of monero merchants.

https://www.minersforless.com/

Thanks
Mark

**Comment by el00ruobuob** [comment]
Well, as a cryptocurrency aiming to be ASIC resistant, I'm a bit confused here. I think other community members point of view would be appreciated here. @SamsungGalaxyPlayer @erciccione ?

**Comment by el00ruobuob** [comment]
Indeed @MInersForLess i get the point. It's just a bit strange to me to list a merchant vending ASIC while in the meantime fighting ASIC in our network upgrades. That's why i asked for others' point of view.
But as we do not endorse any of the listed sites, it should be just fine. I just want others to share their feelings here.

**Comment by erciccione** [comment]
I don't think it's a problem. As you said, being listed on getmonero doesn't mean endorsement.

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by erciccione** [comment]
+resolved
