### ISSUE TITLE
Remove all JavaScript tracking (Piwik, Matomo)

### ISSUE THREAD

**Issue by selsta** [monero-project/monero-site#978]
Monero as a a privacy coin should lead by example and remove all JavaScript tracking from their website.

Basic analytics can be extracted from webserver logs, Matomo even supports this: https://matomo.org/log-analytics/

**Comment by erciccione** [comment]
Important to note that Matomo hasn't been working for some time (#945).

I would find very useful to have info about what people visit on getmonero, the language they speak and where the people come from (meaning, what website directed them to getmonero.org), so to be able to make aimed changes and improvements to the website.

If these info can be retrieved from server logs using Matomo (and from a quick look, seems like it does), i agree with removing all JS based tracking, otherwise better discuss an alternative.

**Comment by selsta** [comment]
> I would find very useful to have info about what people visit on getmonero, the language they speak and where the people come from (meaning, what website directed them to getmonero.org), so to be able to make aimed changes and improvements to the website.

All of this should be possible with log parsing.

**Comment by erciccione** [comment]
@danrmiller could you set up Matomo to only use the server logs?
